### ISSUE TITLE
2 Capitulo,. Código: hello_server3.js

### ISSUE THREAD

**Issue by A4gara** [caio-ribeiro-pereira/livro-nodejs#19]
O Código por algum motivo apresenta o seguinte erro no terminal:

 nodejs hello_server3.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1135:5)
    at Object.<anonymous> (/media/alexandre/1TB/Estudar/Programação/node.js/Codigos/Cap2/hello_server3.js:18:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

Eu não entendi o por que do erro, já que o código que eu usei e o mesmo do livro e o mesmo do github.

**Comment by A4gara** [comment]
Como eu expliquei no meu commit que fiz eu efetuei a troca da porta para 3001 ja que a porta 3000 por algum motivo estava ocupada.

**Comment by caio-ribeiro-pereira** [comment]
Ola Alexandre, o codigo nao tem problemas, na vdd esse erro so acontece
quando uma porta da rede ja esta ocupada, e provavelmente vc deve ter algum
processo ja rodando nessa porta.

Att,
Caio Ribeiro Pereira
Software Engineer
http://crpwebdev.com
