### ISSUE TITLE
Capitulo 4 - Aplicação de Chat não starta

### ISSUE THREAD

**Issue by diego3** [caio-ribeiro-pereira/livro-nodejs#39]
Olha eu denovo hehe!

agora tento rodar a aplicação conforme ensinado no livro dessa forma:

```bash
cd ntalk
npm start
```

mas parece q éh lançada uma exceção/erro
olha o log
```java
0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.14.20
3 info using node@v4.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart ntalk@1.0.0
6 info start ntalk@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info ntalk@1.0.0 Failed to exec start script
9 verbose stack Error: ntalk@1.0.0 start: `node server`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (c:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (c:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid ntalk@1.0.0
11 verbose cwd d:\livro-nodejs\projeto\ntalk
12 error Windows_NT 6.3.9600
13 error argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.4.0
15 error npm  v2.14.20
16 error code ELIFECYCLE
17 error ntalk@1.0.0 start: `node server`
17 error Exit status 1
18 error Failed at the ntalk@1.0.0 start script 'node server'.
18 error This is most likely a problem with the ntalk package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node server
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs ntalk
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls ntalk
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

```
tem até um print do meu cmd :)

![node_error](https://cloud.githubusercontent.com/assets/7679729/13814966/699a367c-eb67-11e5-8e27-c7fa4ce37b41.png)

**Comment by caio-ribeiro-pereira** [comment]
Ola amigo, poderia me passar o link github do seu projeto para eu ver todos
os códigos do seu ntalk?

Regards,
Caio Ribeiro Pereira
About: http://crpwebdev.com
