### ISSUE TITLE
Erro a rodar projeto do capitulo quatro

### ISSUE THREAD

**Issue by pmargreff** [caio-ribeiro-pereira/livro-nodejs#42]
De acordo com o que ví nos erros anteriores o que está acontecendo comigo é diferente. Segue:

```
> ntalk@1.0.0 start /home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk
> node server

Ntalk no ar.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/socket.io-redis/node_modules/redis/index.js:185:24)
    at Socket.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/socket.io-redis/node_modules/redis/index.js:95:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Ntalk no ar.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/socket.io-redis/node_modules/redis/index.js:185:24)
    at Socket.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/socket.io-redis/node_modules/redis/index.js:95:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Ntalk no ar.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: failed to connect to [undefined:27017]
    at null.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
Ntalk no ar.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: failed to connect to [undefined:27017]
    at null.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
Ntalk no ar.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/socket.io-redis/node_modules/redis/index.js:185:24)
    at Socket.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/socket.io-redis/node_modules/redis/index.js:95:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Ntalk no ar.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/socket.io-redis/node_modules/redis/index.js:185:24)
    at Socket.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/socket.io-redis/node_modules/redis/index.js:95:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Ntalk no ar.


```

Alguém pode me ajudar com isso?

**Comment by caio-ribeiro-pereira** [comment]
Vc precisa instalar o redis ou caso ele ja esteja instalado, vc precisa
iniciar o serviço redis-server

Regards,
Caio Ribeiro Pereira
About: http://crpwebdev.com
On May 30, 2016 21:55, "Pablo Margreff" <notifications@github.com> wrote:

De acordo com o que ví nos erros anteriores o que está acontecendo comigo é
diferente. Segue:

> ntalk@1.0.0 start /home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk
> node server

Ntalk no ar.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error
(/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/socket.io-redis/node_modules/redis/index.js:185:24)
    at Socket.<anonymous>
(/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/socket.io-redis/node_modules/redis/index.js:95:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Ntalk no ar.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error
(/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/socket.io-redis/node_modules/redis/index.js:185:24)
    at Socket.<anonymous>
(/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/socket.io-redis/node_modules/redis/index.js:95:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Ntalk no ar.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: failed to connect to [undefined:27017]
    at null.<anonymous>
(/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous>
(/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous>
(/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
Ntalk no ar.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: failed to connect to [undefined:27017]
    at null.<anonymous>
(/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous>
(/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous>
(/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
Ntalk no ar.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error
(/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/socket.io-redis/node_modules/redis/index.js:185:24)
    at Socket.<anonymous>
(/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/socket.io-redis/node_modules/redis/index.js:95:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Ntalk no ar.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error
(/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/socket.io-redis/node_modules/redis/index.js:185:24)
    at Socket.<anonymous>
(/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/socket.io-redis/node_modules/redis/index.js:95:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Ntalk no ar.



Alguém pode me ajudar com isso?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/caio-ribeiro-pereira/livro-nodejs/issues/42>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAhpPHWFmNtpRgcoKSdFxeI4MaL0Wl9cks5qG4cVgaJpZM4IqGTi>
.

**Comment by pmargreff** [comment]
Instalei o redis-server e rodei mais ainda estou recebendo o mesmo erro, segue anexo o arquivo de LOG. 


```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: failed to connect to [undefined:27017]
    at null.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: failed to connect to [undefined:27017]
    at null.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: failed to connect to [undefined:27017]
    at null.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: failed to connect to [undefined:27017]
    at null.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: failed to connect to [undefined:27017]
    at null.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: failed to connect to [undefined:27017]
    at null.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: failed to connect to [undefined:27017]
    at null.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: failed to connect to [undefined:27017]
    at null.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: failed to connect to [undefined:27017]
    at null.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: failed to connect to [undefined:27017]
    at null.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/home/pmargreff/Dropbox/classes/node/livro-nodejs/projeto/ntalk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)

```

**Comment by caio-ribeiro-pereira** [comment]
Fala Pablo blz?

Esse erro esta referente a conexão com MongoDB, afinal a porta 27017 é default do mongodb, porém tem um "undefined" no meio da url, talvez vc esteja com config.js incorreto, pois o certo seria aparecer "localhost:27017", você também instalou o MongoDB?
Poderia me mostrar o github do seu projeto para eu fazer uma analise completa?

Abs!  

Regards,
Caio Ribeiro Pereira
Developer, blogger and writter
About: http://crpwebdev.com
Blog: http://udgwebdev.com

**Comment by pmargreff** [comment]
Erro encontrado na [Issue 8](https://github.com/caio-ribeiro-pereira/livro-nodejs/issues/8).
